# Generated by Django 3.2.12 on 2023-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(blank=True, max_length=100)),
                ('image_url', models.JSONField(blank=True)),
                ('image_count', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('top_description_text', models.CharField(blank=True, max_length=100)),
                ('middle_description_text', models.CharField(blank=True, max_length=100)),
                ('bottom_description_text', models.CharField(blank=True, max_length=100)),
                ('red_text', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('action_payload', models.JSONField(blank=True)),
                ('checkable', models.BooleanField(blank=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('label_color', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True)),
                ('standard_label_color', models.CharField(blank=True, max_length=100)),
                ('is_checked', models.BooleanField(blank=True)),
                ('has_divider', models.BooleanField(blank=True)),
                ('padded', models.BooleanField(blank=True)),
                ('has_chat', models.BooleanField(blank=True)),
                ('token', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
