# Generated by Django 3.2.12 on 2023-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrow',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
